packages:
  - apps/*
  - packages/*

catalog:
  # Shared tooling
  '@tuyau/core': 1.0.0-beta.13
  ts-pattern: ^5.9.0

  # React
  react: ^19.2.4
  react-dom: ^19.2.4
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3

  # TypeScript
  typescript: ^5.9.3
  '@types/node': ^25.2.2

  # Tailwind
  tailwindcss: ^4.1.18
  '@tailwindcss/vite': ^4.1.18
