/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125AuthRouteRouteImport } from './routes/{-$locale}/auth/route'
import { Route as Char123LocaleChar125dashboardRouteRouteImport } from './routes/{-$locale}/(dashboard)/route'
import { Route as Char123LocaleChar125dashboardIndexRouteImport } from './routes/{-$locale}/(dashboard)/index'
import { Route as Char123LocaleChar125dashboardAdminRouteRouteImport } from './routes/{-$locale}/(dashboard)/admin/route'
import { Route as Char123LocaleChar125AuthVerifyEmailIndexRouteImport } from './routes/{-$locale}/auth/verify-email/index'
import { Route as Char123LocaleChar125AuthSignupIndexRouteImport } from './routes/{-$locale}/auth/signup/index'
import { Route as Char123LocaleChar125AuthResetPasswordIndexRouteImport } from './routes/{-$locale}/auth/reset-password/index'
import { Route as Char123LocaleChar125AuthResendVerificationIndexRouteImport } from './routes/{-$locale}/auth/resend-verification/index'
import { Route as Char123LocaleChar125AuthLoginIndexRouteImport } from './routes/{-$locale}/auth/login/index'
import { Route as Char123LocaleChar125AuthForgotPasswordIndexRouteImport } from './routes/{-$locale}/auth/forgot-password/index'
import { Route as Char123LocaleChar125dashboardAdminIndexRouteImport } from './routes/{-$locale}/(dashboard)/admin/index'

const Char123LocaleChar125AuthRouteRoute =
  Char123LocaleChar125AuthRouteRouteImport.update({
    id: '/{-$locale}/auth',
    path: '/{-$locale}/auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125dashboardRouteRoute =
  Char123LocaleChar125dashboardRouteRouteImport.update({
    id: '/{-$locale}/(dashboard)',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125dashboardIndexRoute =
  Char123LocaleChar125dashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125dashboardRouteRoute,
  } as any)
const Char123LocaleChar125dashboardAdminRouteRoute =
  Char123LocaleChar125dashboardAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125dashboardRouteRoute,
  } as any)
const Char123LocaleChar125AuthVerifyEmailIndexRoute =
  Char123LocaleChar125AuthVerifyEmailIndexRouteImport.update({
    id: '/verify-email/',
    path: '/verify-email/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthSignupIndexRoute =
  Char123LocaleChar125AuthSignupIndexRouteImport.update({
    id: '/signup/',
    path: '/signup/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthResetPasswordIndexRoute =
  Char123LocaleChar125AuthResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthResendVerificationIndexRoute =
  Char123LocaleChar125AuthResendVerificationIndexRouteImport.update({
    id: '/resend-verification/',
    path: '/resend-verification/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthLoginIndexRoute =
  Char123LocaleChar125AuthLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125AuthForgotPasswordIndexRoute =
  Char123LocaleChar125AuthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125dashboardAdminIndexRoute =
  Char123LocaleChar125dashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125dashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125dashboardRouteRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteRouteWithChildren
  '/{-$locale}/admin': typeof Char123LocaleChar125dashboardAdminRouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125dashboardIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125dashboardAdminIndexRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordIndexRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginIndexRoute
  '/{-$locale}/auth/resend-verification': typeof Char123LocaleChar125AuthResendVerificationIndexRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordIndexRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupIndexRoute
  '/{-$locale}/auth/verify-email': typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125dashboardIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125dashboardAdminIndexRoute
  '/{-$locale}/auth/forgot-password': typeof Char123LocaleChar125AuthForgotPasswordIndexRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginIndexRoute
  '/{-$locale}/auth/resend-verification': typeof Char123LocaleChar125AuthResendVerificationIndexRoute
  '/{-$locale}/auth/reset-password': typeof Char123LocaleChar125AuthResetPasswordIndexRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupIndexRoute
  '/{-$locale}/auth/verify-email': typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/(dashboard)': typeof Char123LocaleChar125dashboardRouteRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRouteRouteWithChildren
  '/{-$locale}/(dashboard)/admin': typeof Char123LocaleChar125dashboardAdminRouteRouteWithChildren
  '/{-$locale}/(dashboard)/': typeof Char123LocaleChar125dashboardIndexRoute
  '/{-$locale}/(dashboard)/admin/': typeof Char123LocaleChar125dashboardAdminIndexRoute
  '/{-$locale}/auth/forgot-password/': typeof Char123LocaleChar125AuthForgotPasswordIndexRoute
  '/{-$locale}/auth/login/': typeof Char123LocaleChar125AuthLoginIndexRoute
  '/{-$locale}/auth/resend-verification/': typeof Char123LocaleChar125AuthResendVerificationIndexRoute
  '/{-$locale}/auth/reset-password/': typeof Char123LocaleChar125AuthResetPasswordIndexRoute
  '/{-$locale}/auth/signup/': typeof Char123LocaleChar125AuthSignupIndexRoute
  '/{-$locale}/auth/verify-email/': typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/auth'
    | '/{-$locale}/admin'
    | '/{-$locale}/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/resend-verification'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/auth'
    | '/{-$locale}'
    | '/{-$locale}/admin'
    | '/{-$locale}/auth/forgot-password'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/resend-verification'
    | '/{-$locale}/auth/reset-password'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/auth/verify-email'
  id:
    | '__root__'
    | '/{-$locale}/(dashboard)'
    | '/{-$locale}/auth'
    | '/{-$locale}/(dashboard)/admin'
    | '/{-$locale}/(dashboard)/'
    | '/{-$locale}/(dashboard)/admin/'
    | '/{-$locale}/auth/forgot-password/'
    | '/{-$locale}/auth/login/'
    | '/{-$locale}/auth/resend-verification/'
    | '/{-$locale}/auth/reset-password/'
    | '/{-$locale}/auth/signup/'
    | '/{-$locale}/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125dashboardRouteRoute: typeof Char123LocaleChar125dashboardRouteRouteWithChildren
  Char123LocaleChar125AuthRouteRoute: typeof Char123LocaleChar125AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/{-$locale}/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(dashboard)': {
      id: '/{-$locale}/(dashboard)'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(dashboard)/': {
      id: '/{-$locale}/(dashboard)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125dashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125dashboardRouteRoute
    }
    '/{-$locale}/(dashboard)/admin': {
      id: '/{-$locale}/(dashboard)/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125dashboardAdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125dashboardRouteRoute
    }
    '/{-$locale}/auth/verify-email/': {
      id: '/{-$locale}/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/{-$locale}/auth/verify-email'
      preLoaderRoute: typeof Char123LocaleChar125AuthVerifyEmailIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/auth/signup/': {
      id: '/{-$locale}/auth/signup/'
      path: '/signup'
      fullPath: '/{-$locale}/auth/signup'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignupIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/auth/reset-password/': {
      id: '/{-$locale}/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/{-$locale}/auth/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthResetPasswordIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/auth/resend-verification/': {
      id: '/{-$locale}/auth/resend-verification/'
      path: '/resend-verification'
      fullPath: '/{-$locale}/auth/resend-verification'
      preLoaderRoute: typeof Char123LocaleChar125AuthResendVerificationIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/auth/login/': {
      id: '/{-$locale}/auth/login/'
      path: '/login'
      fullPath: '/{-$locale}/auth/login'
      preLoaderRoute: typeof Char123LocaleChar125AuthLoginIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/auth/forgot-password/': {
      id: '/{-$locale}/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/{-$locale}/auth/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125AuthForgotPasswordIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/(dashboard)/admin/': {
      id: '/{-$locale}/(dashboard)/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125dashboardAdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125dashboardAdminRouteRoute
    }
  }
}

interface Char123LocaleChar125dashboardAdminRouteRouteChildren {
  Char123LocaleChar125dashboardAdminIndexRoute: typeof Char123LocaleChar125dashboardAdminIndexRoute
}

const Char123LocaleChar125dashboardAdminRouteRouteChildren: Char123LocaleChar125dashboardAdminRouteRouteChildren =
  {
    Char123LocaleChar125dashboardAdminIndexRoute:
      Char123LocaleChar125dashboardAdminIndexRoute,
  }

const Char123LocaleChar125dashboardAdminRouteRouteWithChildren =
  Char123LocaleChar125dashboardAdminRouteRoute._addFileChildren(
    Char123LocaleChar125dashboardAdminRouteRouteChildren,
  )

interface Char123LocaleChar125dashboardRouteRouteChildren {
  Char123LocaleChar125dashboardAdminRouteRoute: typeof Char123LocaleChar125dashboardAdminRouteRouteWithChildren
  Char123LocaleChar125dashboardIndexRoute: typeof Char123LocaleChar125dashboardIndexRoute
}

const Char123LocaleChar125dashboardRouteRouteChildren: Char123LocaleChar125dashboardRouteRouteChildren =
  {
    Char123LocaleChar125dashboardAdminRouteRoute:
      Char123LocaleChar125dashboardAdminRouteRouteWithChildren,
    Char123LocaleChar125dashboardIndexRoute:
      Char123LocaleChar125dashboardIndexRoute,
  }

const Char123LocaleChar125dashboardRouteRouteWithChildren =
  Char123LocaleChar125dashboardRouteRoute._addFileChildren(
    Char123LocaleChar125dashboardRouteRouteChildren,
  )

interface Char123LocaleChar125AuthRouteRouteChildren {
  Char123LocaleChar125AuthForgotPasswordIndexRoute: typeof Char123LocaleChar125AuthForgotPasswordIndexRoute
  Char123LocaleChar125AuthLoginIndexRoute: typeof Char123LocaleChar125AuthLoginIndexRoute
  Char123LocaleChar125AuthResendVerificationIndexRoute: typeof Char123LocaleChar125AuthResendVerificationIndexRoute
  Char123LocaleChar125AuthResetPasswordIndexRoute: typeof Char123LocaleChar125AuthResetPasswordIndexRoute
  Char123LocaleChar125AuthSignupIndexRoute: typeof Char123LocaleChar125AuthSignupIndexRoute
  Char123LocaleChar125AuthVerifyEmailIndexRoute: typeof Char123LocaleChar125AuthVerifyEmailIndexRoute
}

const Char123LocaleChar125AuthRouteRouteChildren: Char123LocaleChar125AuthRouteRouteChildren =
  {
    Char123LocaleChar125AuthForgotPasswordIndexRoute:
      Char123LocaleChar125AuthForgotPasswordIndexRoute,
    Char123LocaleChar125AuthLoginIndexRoute:
      Char123LocaleChar125AuthLoginIndexRoute,
    Char123LocaleChar125AuthResendVerificationIndexRoute:
      Char123LocaleChar125AuthResendVerificationIndexRoute,
    Char123LocaleChar125AuthResetPasswordIndexRoute:
      Char123LocaleChar125AuthResetPasswordIndexRoute,
    Char123LocaleChar125AuthSignupIndexRoute:
      Char123LocaleChar125AuthSignupIndexRoute,
    Char123LocaleChar125AuthVerifyEmailIndexRoute:
      Char123LocaleChar125AuthVerifyEmailIndexRoute,
  }

const Char123LocaleChar125AuthRouteRouteWithChildren =
  Char123LocaleChar125AuthRouteRoute._addFileChildren(
    Char123LocaleChar125AuthRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125dashboardRouteRoute:
    Char123LocaleChar125dashboardRouteRouteWithChildren,
  Char123LocaleChar125AuthRouteRoute:
    Char123LocaleChar125AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
